const SUCCESS = {
    OK: "OK",
    CREATED: "CREATED"
}

const ERROR = {
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    CONFLICT: "CONFLICT",
    EXPECTATION_FAILED: "EXPECTATION_FAILED",
    FORBIDDEN: "FORBIDDEN",
    UNAUTHORIZED: "UNAUTHORIZED",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT"
};

module.exports = { ERROR, SUCCESS };